[project]
name = "hydra-ssh"
version = "1.0.0"
description = "A command-line tool to execute commands on multiple remote hosts"
authors = [
    {name = "Chaiwat Suttipongsakul",email = "cwt@bashell.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncssh (>=2.20.0,<3.0.0)",
    "uvloop (>=0.21.0,<0.22.0) ; sys_platform != \"win32\"",
    "winloop (>=0.1.8,<0.2.0) ; sys_platform == \"win32\""
]

[tool.poetry]
repository = "https://github.com/cwt/hydra"

[tool.poetry.scripts]
hydra-ssh = "hydra_ssh.hydra:run_cli"

[tool.poetry.group.dev.dependencies]
mypy = "^1.15.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
