[tool.poetry]
name = "ros2-lifecycle-package-creator"
version = "0.1.3"
description = "Create ROS2 lifecycle package boilerplate from a minimal config file"
authors = ["Myron Rodrigues <rodriguesmyron47@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
include = [
    { path = "ros2_lifecycle_package_creator/templates/*", format = ["sdist", "wheel"] },
    { path = "ros2_lifecycle_package_creator/package_files/*", format = ["sdist", "wheel"] }
]

[tool.poetry.dependencies]
python = "^3.10"
Jinja2 = "^3.1.4"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ros2-lifecycle-pkg-create = "ros2_lifecycle_package_creator.main:main"