[project]
name = "nonebot_plugin_suggarchat"
version = "1.15.5"
description = "Plugin for the Suggar chat framework compatible with Nonebot2."
authors = [
    { name = "JohnRichard4096", email = "windowserror@163.com" },
]
dependencies = [
    "jieba>=0.42.1",
    "nonebot2>=2.2.0",
    "openai>=1.5.0",
    "pydantic>=2.4.2",
    "nonebot-adapter-onebot>=2.0.0",
    "nonebot-plugin-localstore>=0.7",
    "nonebot_plugin_uninfo>=0.4.1",
    "chardet>=5.1.0",
    "typing-extensions>=4.6.0",
    "pytz>=2025.1",
]
requires-python = ">=3.9, <4.0"
readme = "README.md"
keywords = [
    "chat\", \"suggar\", \"nonebot",
]

[project.license]
text = "GPL-3.0-or-later"

[project.urls]
Homepage = "https://github.com/JohnRichard4096/nonebot_plugin_suggarchat"
Source = "https://github.com/JohnRichard4096/nonebot_plugin_suggarchat"
"Issue Tracker" = "https://github.com/JohnRichard4096/nonebot_plugin_suggarchat/issues"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
