[tool.poetry]
name = "hestonpy"
version = "0.5.6"
description = "Heston models: pricing, calibration, hedging."
authors = ["SarcasticMatrix"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.2.3"
scipy = "^1.15.2"
matplotlib = "^3.10.1"
pandas = "^2.2.3"
tqdm = "^4.67.1"
datetime = "^5.5"
yfinance = "^0.2.54"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
