[project]
authors = [{name = "Jared Galloway", email = "jaredgalloway07@gmail.com"}]
dependencies = ["numpy"]
name = "jareds_super_ai"
requires-python = ">= 3.11"
version = "0.0.2"
scripts = {generate-wisdom = "jareds_super_ai:main"}

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
jareds_super_ai = { path = ".", editable = true }

[tool.pixi.tasks]
