[build-system]
requires = [
    "hatchling>=1.27.0"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_db"
version = "2.1.0"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (database modules)"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "pypomes_core>=1.9.9"
#   "mysql-connector-python>=9.2.0"
#   "oracledb>=3.0.0"
#   "psycopg2-binary>=2.9.10"
#   "pyodbc>=5.2.0"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-DB"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-DB/issues"
