[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pychemstation"
version = "0.8.2"
description = ""
authors = [{ name = "lucyhao", email = "hao.lucyy@gmail.com" }]
requires-python = ">=3.8"
readme = "README.md"
dependencies = [
    "aghplctools>=4.8.8",
    "coverage>=7.6.1",
    "matplotlib>=3.7.5",
    "pandas>=2.0.3",
    "pdoc>=14.7.0",
    "polling>=0.3.2",
    "pytest>=7.3.5",
    "rainbow-api>=1.0.10",
    "result>=0.17.0",
    "scipy>=1.10.1",
    "seabreeze>=2.9.2",
    "setuptools>=75.3.2",
    "twine>=6.1.0",
    "xsdata>=24.9",
]

[dependency-groups]
dev = ["mypy>=1.14.1,<2"]
