[project]
name = "convert-poetry2uv"
version = "0.2.2"
description = "Poetry to uv tool. To migrate from a poetry managed repo to uv."
authors = [{ "name" = "Bart", "email" = "bart@bamweb.nl" }]
readme = "README.md"
requires-python = ">=3.12"

dependencies = ["tomlkit>=0.13.2"]

[dependency-groups]
dev = [
    "bump2version>=1.0.1",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
]

[project.scripts]
convert-poetry2uv = "convert_poetry2uv:main"
convert_poetry2uv = "convert_poetry2uv:main"

[tool.uv]
package = true

[project.urls]
"Pull Requests" = "https://github.com/bartdorlandt/convert_poetry2uv/pulls"
"Bug Tracker" = "https://github.com/bartdorlandt/convert_poetry2uv/issues"
"Changelog" = "https://github.com/bartdorlandt/convert_poetry2uv/blob/main/CHANGELOG.md"
"Repository" = "https://github.com/bartdorlandt/convert_poetry2uv"
