[project]
name = "midii"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ccsss", email = "chansol0505@naver.com" }
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
    "mido>=1.3.3",
    "numpy>=2.2.4",
    "pydub>=0.25.1",
    "rich>=13.9.4",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
