[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["assets", "examples", "docker", "notebooks", "tests"]

[project]
name = "rag-colls"
version = "0.2.0"
description = "rag-colls - Implement recent advanced RAG techniques"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bm25s>=0.2.10",
    "chromadb>=0.6.3",
    "elasticsearch[async]>=8.17.2",
    "gdown>=5.2.0",
    "jax[cpu]>=0.5.3",
    "litellm>=1.65.0",
    "llama-index-embeddings-openai>=0.3.1",
    "loguru>=0.7.3",
    "platformdirs>=4.3.7",
    "pymupdf>=1.25.4",
    "rich>=13.9.4",
    "tenacity>=9.0.0",
]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[project.urls]
Homepage = "https://github.com/hienhayho/rag-colls"
Issues = "https://github.com/hienhayho/rag-colls/issues"
