[project]
name = "azure-subscription-switcher"
version = "0.3.1"
description = "CLI Utility tool to switch between azure subscriptions"
authors = [
    {name = "Lahiru Senevirathne",email = "lahiru.senevirathne@icloud.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]
license="MIT"

[tool.poetry]
packages = [{include = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
click = "^8.1.3"
python= ">=3.9"

[tool.poetry.scripts]
azsub = "src.app:main"