[project]
name = "jmcomic_api"
version = "0.5.0"
description = "A Python crawler for downloading content from JMComic."
authors = [
    {name = "Shua", email = "CHA_shua@outlook.com"},
]
dependencies = [
    "fastapi>=0.115.12",
    "jmcomic>=2.5.32",
    "PyYAML>=6.0",
    "uvicorn>=0.34.0",
    "img2pdf>=0.6.0",
    "colorlog>=6.7.0",
    "pydantic>=2.11.0",
    "pypdf>=5.4.0",
    "requests>=2.32.3",
    "pyzipper>=0.3.6",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
jmcomic-api-server = "jmcomic_api:main"

# 使用 setuptools 作为构建系统
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# 包信息，动态发现包
[tool.setuptools.packages]
find = {where = ["."], exclude = ["tests*"]}  # 动态发现包，排除测试文件

[tool.pdm.scripts]
dev = {call = "jmcomic_api:main", env = {DEV = "true"} } # dev启动
start = {call = "jmcomic_api:main"} # 正常启动
uninstall = "pdm remove" # 卸载
install = "pdm add" # 安装
build = "pdm build" # 打包
format = 'ruff format .' # 格式化
check = 'ruff check .' # 格式化
publish = 'twine upload dist/*' # 上传pypi

[dependency-groups]
dev = [
    "jurigged>=0.6.0",
    "ruff>=0.11.2",
    "twine>=6.1.0",
]
