[project]
name = "textnets"
version = "0.10.0"
authors = [
    { name = "John D. Boy", email = "jboy@bius.moe" },
]
license = "GPL-3.0-only"
description = "Automated text analysis with networks"
readme = "README.rst"
keywords = [
    "computational social science",
    "network analysis",
    "nlp",
    "text analysis",
    "visualization",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Programming Language :: Cython",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Sociology",
]
requires-python = "<3.13,>=3.10"
dependencies = [
    "igraph",
    "leidenalg",
    "pandas<3.0.0,>=2.2.3",
    "scipy<2.0.0,>=1.14.1",
    "spacy<4.0.0,>=3.8.3",
    "spacy-lookups-data<2.0.0,>=1.0.5",
    "toolz<1.0.0,>=0.12.1",
    "tqdm<5.0.0,>=4.66.5",
    "wasabi<2.0.0,>=1.1.3",
    "pyarrow<19.0.0,>=18.0.1; implementation_name != \"pypy\"",
    "matplotlib<4.0.0,>=3.10.1",
]

[project.urls]
"Bug Tracker" = "https://github.com/jboynyc/textnets/issues"
Changelog = "https://textnets.readthedocs.io/en/stable/history.html"
Documentation = "https://textnets.readthedocs.io"
homepage = "https://textnets.readthedocs.io"
repository = "https://github.com/jboynyc/textnets"

[project.optional-dependencies]
zh = [
    "jieba>=0.42.1,<1.0.0",
]

[build-system]
requires = [
    "Cython>=0.29",
    "pdm-backend",
    "setuptools>=49",
]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = [
    "textnets/_ext*.so",
    "docs/*.py",
    "docs/refs.bib",
    "docs/*.rst",
    "docs/_static",
    "docs/*.svg",
    "LICENSE",
    "*.rst",
    "tests/*.py",
]
run-setuptools = true

[tool.pdm.dev-dependencies]
dev = [
    "coverage>=7.6.1",
    "pdm-bump>=0.9.11.post2",
]
doc = [
    "en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl",
    "ipykernel<7.0.0,>=6.29.5",
    "jupyter-sphinx>=0.5.0",
    "shibuya<2026.0.0,>=2025.3.24",
    "sphinx<8.0.0,>=7.4.7",
    "sphinxcontrib-bibtex<3.0.0,>=2.6.3",
]
lint = [
    "flake8<8.0.0,>=7.1.1",
    "ufmt<3.0.0,>=2.7.3",
]
test = [
    "en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl",
    "pytest<9.0.0,>=8.3.3",
]
typing = [
    "mypy<2.0.0,>=1.11.2",
    "pandas-stubs<3.0.0.0,>=2.2.2.240909",
]

[tool.pdm.plugin.bump]
commit_msg_tpl = "Bump to version {to}"

[tool.mypy]
files = "textnets"
warn_unused_ignores = true
warn_unreachable = true
ignore_missing_imports = true
pretty = true

[tool.ufmt]
excludes = [
    "textnets/_ext*.so",
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:invalid escape sequence:DeprecationWarning",
]
