component:
  flow_name: elt
  metadata:
    source:
      first_line_number: 8
      path: projects/bigquery/flows/elt/components/routes.py
  name: routes
  tests: {}
  transform:
    inputs:
    - flow: elt
      name: read_routes
    lookback: 1
    microbatch: false
    python:
      entrypoint: routes.routes
      source: flows/elt/components/routes.py
    strategy:
      partitioned:
        enable_substitution_by_partition_name: false
        output_type: table