component:
  flow_name: elt
  metadata:
    source:
      first_line_number: 8
      path: projects/bigquery/flows/elt/components/weather_routes.py
  name: weather_routes
  tests: {}
  transform:
    inputs:
    - flow: elt
      name: read_weather_routes
    lookback: 1
    microbatch: false
    python:
      entrypoint: weather_routes.weather_routes
      source: flows/elt/components/weather_routes.py
    strategy:
      partitioned:
        enable_substitution_by_partition_name: false
        output_type: table