[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "an_quickviper2"
version = "1.1.0"
description = "A package for an_quickviper2."
authors = [
    { name = "Atsushi888", email = "vtgrotxu@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.6"
dependencies = ['an_DebugHelper>=1.2.3,<2.0.0', 'an_EasyVen>=0.1.5,<1.0.0', 'an_UniqueEnvVar>=0.1.5,<1.0.0']

[project.urls]
Homepage = "https://github.com/Atsushi888/an_quickviper2"
Repository = "https://github.com/Atsushi888/an_quickviper2"
