[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "j_kuant"
version = "0.1.13"
description = "A test package for Jupyter-based quantum work"
readme = "README.md"
license = "MIT"
authors = [
    { name="Jeremy", email="jeremy@vconn.org" }
]
dependencies = []
requires-python = ">=3.7"

[tool.setuptools.packages.find]
where = ["."]
