[project]
name = "HTAN-h5ad-validate"
description = "Validates AnnData h5ad files for adherence to HTAN sc/snRNA-seq requirements."
requires-python = ">=3.8"
version = "0.1.0"
license = { file = "LICENSE.txt" }
readme = "README.md"
keywords = ["HTAN", "HTAN sc/snRNA-seq", "HTAN h5ad"]
dependencies = [
    "anndata==0.10.8",
    "array_api_compat==1.11",
    "cellxgene-schema==5.2.3",
    "cellxgene_ontology_guide==1.2.0",
    "click==8.1.8",
    "contourpy==1.3.1",
    "cycler==0.12.1",
    "Cython==3.0.12",
    "fonttools==4.56.0",
    "h5py==3.13.0",
    "kiwisolver==1.4.8",
    "matplotlib==3.10.1",
    "natsort==8.4.0",
    "numpy==1.26.4",
    "packaging==24.2",
    "pandas==2.2.3",
    "pillow==11.1.0",
    "pyparsing==3.2.1",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.1",
    "PyYAML==6.0.2",
    "scipy==1.14.1",
    "semantic-version==2.10.0",
    "semver==3.0.4",
    "six==1.17.0",
    "tzdata==2025.1",
    "xxhash==3.5.0"
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.5"
]

[build-system]
requires = ["setuptools==69"]
build-backend = "setuptools.build_meta"

[project.scripts]
HTAN-h5ad-validate = "h5ad_validate:validate.run_validate"

[project.urls]
Repository = "https://github.com/ncihtan/h5ad"