[tool.poetry]
name = "givernylocal"
version = "3.1.7"
description = "library to query the Johns Hopkins Turbulence Database (JHTDB) datasets"
authors = ["Johns Hopkins Turbulence Database Group"]
license = "LICENSE.txt"
readme = "README.md"

[[tool.poetry.packages]]
include = "givernylocal"
from = "src"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.4"
matplotlib = "^3.6.2"
pydantic = "^2.10.6"
pandas = "^1.5.1"
requests = "^2.31.0"
tenacity = "^8.1.0"
plotly = "^5.11.0"
attrs = "^23.2.0"
jsonschema = "^4.23.0"
jsonschema-specifications = "^2023.12.1"
nbformat = "^5.10.4"
referencing = "^0.35.1"
rpds-py = "^0.19.1"
jupyter-core = "^5.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Homepage" = "https://github.com/sciserver/giverny"
"Bug Tracker" = "https://github.com/sciserver/giverny/issues"
"Changelog" = "https://github.com/sciserver/giverny/blob/main/CHANGELOG.md"
