[project]
name = "baidu-maps"
version = "0.0.1"
description = "Baidu Maps MCP Server"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "baidu-maps" }]
maintainers = [{ name = "Pineapple274", email = "yuyangyang3838@gmail.com" }]
keywords = ["http", "mcp", "map", "baidu"]
license = { text = "MIT" }
dependencies = [
    "asyncio>=3.4.3",
    "httpx>=0.28.1",
    "mcp[cli]>=1.5.0",
]

[project.scripts]
baidu-maps = "baidu_maps:main"

