[tool.poetry]
name = "blech"
version = "0.1.0"
description = "BLECH is a tool designed to automatically identify and extract links to individual posts from a blog's main page, index, or feed. After identifying the links, it proceeds to fetch and parse the content of each blog post, making it easier to process, analyze, or archive blog data."
authors = ["jkarenko <juho.karenko@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/jkarenko/blog-crawler"
repository = "https://github.com/jkarenko/blog-crawler"
keywords = ["blog", "scraper", "content extraction", "web scraping", "cli"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Text Processing",
    "Topic :: Utilities",
]
packages = [{ include = "blech" }]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"

[tool.poetry.scripts]
blech = "blech.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 
