[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ingot-ppm"
version = "1.1"
license = "MIT"
keywords = ["package manager", "dependency management", "python"]
project_urls = {"Homepage" = "https://github.com/IngotStudio/ppm", "Bug Tracker" = "https://github.com/IngotStudio/ppm/issues"}
description = "A faster and more comprehensive Python package manager"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10"
]
authors = [{name = "IngotStudio", email = "xmz_20130612@163.com"}]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "aiohttp>=3.8.0",
    "rich>=10.0.0",
    "packaging>=21.0",
    "tomli>=2.0.0",
    "click>=8.0.0"
]

[project.scripts]
ppm = "ppm.cli:main"
ingot-ppm = "ppm.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["ppm"]

[tool.hatch.envs.default]
dependencies = [
    "build",
    "twine"
]

[tool.hatch.publish.index]
repo = "testpypi"
repo-url = "https://test.pypi.org/legacy/"
