[project]
name = "funcnodes-webcam"
version = "0.1.3"
description = ""
readme = "README.md"
dependencies = [
 "funcnodes-opencv>=0.2.17",
 "funcnodes>=0.5.36",
 "funcnodes-worker>=0.3.1",
]
requires-python = ">=3.11"
[[project.authors]]
name = "Julian Kimmig"
email = "julian.kimmig@gmx.net"

[dependency-groups]
dev = [
 "jupyterlab>=4.1.2",
 "matplotlib>=3.8.3",
 "pre-commit",
 "pytest",
 "funcnodes-module",
 "funcnodes[profiling]>=0.5.35",
]

[build-system]
requires = [ "setuptools>=42",]
build-backend = "setuptools.build_meta"

[project.license]
text = "AGPL-3.0"


[project.urls]
homepage = "https://github.com/Linkdlab/funcnodes_webcam"
source = "https://github.com/Linkdlab/funcnodes_webcam"
tracker = "https://github.com/Linkdlab/funcnodes_webcam/issues"
download = "https://pypi.org/project/funcnodes-webcam/#files"

[tool.setuptools.package-dir]
"" = "src"

[project.entry-points."funcnodes.module"]
module = "funcnodes_webcam"
shelf = "funcnodes_webcam:NODE_SHELF"
external_worker = "funcnodes_webcam:FUNCNODES_WORKER_CLASSES"

[tool.setuptools.packages.find]
where = [ "src",]
