[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=77.0.3"]

[project]
name = "types-editdistance"
version = "0.8.0.20250401"
license = "Apache-2.0"
license-files = ["LICENSE"]
description = "Typing stubs for editdistance"
readme = { text = """\
## Typing stubs for editdistance

This is a [PEP 561](https://peps.python.org/pep-0561/)
type stub package for the [`editdistance`](https://github.com/roy-ht/editdistance) package.
It can be used by type-checking tools like
[mypy](https://github.com/python/mypy/),
[pyright](https://github.com/microsoft/pyright),
[pytype](https://github.com/google/pytype/),
[Pyre](https://pyre-check.org/),
PyCharm, etc. to check code that uses `editdistance`. This version of
`types-editdistance` aims to provide accurate annotations for
`editdistance==0.8.*`.

This package is part of the [typeshed project](https://github.com/python/typeshed).
All fixes for types and metadata should be contributed there.
See [the README](https://github.com/python/typeshed/blob/main/README.md)
for more details. The source for this package can be found in the
[`stubs/editdistance`](https://github.com/python/typeshed/tree/main/stubs/editdistance)
directory.

This package was tested with
mypy 1.15.0,
pyright 1.1.398,
and pytype 2024.10.11.
It was generated from typeshed commit
[`bfd032156c59bbf851f62174014f24f4f89b96af`](https://github.com/python/typeshed/commit/bfd032156c59bbf851f62174014f24f4f89b96af).
""", content-type = "text/markdown" }
classifiers = [
  "Programming Language :: Python :: 3",
  "Typing :: Stubs Only",
]
requires-python = ">=3.9"
dependencies = []

[project.urls]
"Homepage" = "https://github.com/python/typeshed"
"GitHub" = "https://github.com/python/typeshed"
"Changes" = "https://github.com/typeshed-internal/stub_uploader/blob/main/data/changelogs/editdistance.md"
"Issue tracker" = "https://github.com/python/typeshed/issues"
"Chat" = "https://gitter.im/python/typing"

[tool.setuptools]
packages = ['editdistance-stubs']
include-package-data = false
