[project]
name = "qanon_mcp"
version = "0.1.2"
authors = [
  { name="Jack Kingsman", email="jack@jackkingsman.me" },
]
license = "MIT"
description = "MCP server for QAnon drops for sociological research"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
]

[project.scripts]
qanon_mcp = "qanon_mcp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/qanon_mcp"]
