[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alpaca-transformer"
version = "0.1.9.1"
description = "A remade version of basic transformers"
authors = [{ name = "RazielMoesch", email = "razielsoccer@gmail.com" }]
#license = { text = "MIT" }  # Correct license format
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
