[project]
name = "deep-knowledge"
version = "0.1.8"
description = "Deep Knowledge introduces a powerful multi-agent system for creating deep, comprehensive summaries of complex content."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-community>=0.3.20",
    "langchain-core>=0.3.47",
    "langchain-google-genai>=2.1.1",
    "langchain-openai>=0.3.9",
    "langchain-pymupdf4llm>=0.2.0",
    "litellm>=1.63.14",
    "loguru>=0.7.3",
    "pypandoc>=1.15",
    "python-decouple>=3.8",
    "python-dotenv>=1.0.1",
    "streamlit>=1.43.2",
    "unstructured>=0.17.2",
]


[tool.setuptools]
packages = ["deep_knowledge"]

[dependency-groups]
dev = [
    "md2pdf>=1.0.1",
    "mistune>=3.1.3",
]
